### PR TITLE
Add Activity viewBinding without view id

### PR DESCRIPTION
**Pull request by agentchen**

### CODE REVIEW

**Comment by kirich1409** [comment]
Hi. What is the use case for that API?

**Comment by agentchen** [comment]
Like `ProfileFragment` in samples, `ProfileActivity` can be simpler.

> ```kotlin
> class ProfileFragment : Fragment(R.layout.profile) {
> 
>     private val viewBinding: ProfileBinding by viewBinding()
> }
> ```
> 
> ```kotlin
> class ProfileActivity : AppCompatActivity(R.layout.profile) {
> 
>     private val viewBinding: ProfileBinding by viewBinding(R.id.container)
> }
> ```
With new api:

```kotlin
class ProfileActivity : AppCompatActivity(R.layout.profile) {

    private val viewBinding: ProfileBinding by viewBinding()
}
```

**Comment by kirich1409** [comment]
I checked such kind of solution before 1.0. Root of a `ViewBinding` must be specified in activity, because it's not obvious what to take. WIth `Fragment` ut's obvious what to take. I don't want to make confusion for activity.

**Comment by premacck** [comment]
@kirich1409 I think we can provide the first view inside the `android.R.id.content` ViewGroup as the default view

```
public inline fun <A : ComponentActivity, T : ViewBinding> ComponentActivity.viewBinding(
  crossinline vbFactory: (View) -> T, crossinline viewProvider: (A) -> View = { window.findViewById<ViewGroup>(android.R.id.content).getChildAt(0) }
): ViewBindingProperty<A, T> {
  return viewBinding { activity: A -> vbFactory(viewProvider(activity)) }
}
```

This is working for Activities with the layoutRes ID passed as parameter.

**Comment by kirich1409** [comment]
@premacck , good idea. I'll try to implement it in 1.4.0

**Comment by premacck** [comment]
@kirich1409 Any ETA on the 1.4.0 release?

**Comment by kirich1409** [comment]
I will work on it during the next week

**Comment by premacck** [comment]
Okay, in the meanwhile, may I offer a PR for the above change? :)

**Comment by kirich1409** [comment]
Yes. It will be good to check another point of view

**Comment by kirich1409** [comment]
Yes. It will be good to check another point of view

**Comment by premacck** [comment]
@kirich1409 Opened #32

**Pull request closed without merging**
