### PR TITLE
fix(Global): clean some codes

### PR DESCRIPTION
**Pull request by josh-meshkorea**

### CODE REVIEW

**Comment by kirich1409** [comment]
I don't understand the motivation for merge the PR. Why do you think the changes are so important?

**Comment by josh-meshkorea** [comment]
I just remove some warnings and think this is looks better
I see you changed some codes to return If

**Comment by kirich1409** [comment]
I prefer not to use return with if expressions.

**Comment by josh-meshkorea** [comment]
If you don't like I won't force you

**Pull request closed without merging**
